### ISSUE TITLE
An "TemporaryNameServerFailure"  error occurred

### ISSUE THREAD

**Issue by dsus-ch** [hendriknielaender/zvm#39] opened 2024-05-20 07:43 UTC
### Zvm Version

0.3.1

### Steps to Reproduce and Observed Behavior

When I use "nvm list" commands, an "TemporaryNameServerFailure"  error occurred

### Expected Behavior

OS Ubuntu 20.04.6 LTS

I made sure there was nothing wrong with the network

But
![image](https://github.com/hendriknielaender/zvm/assets/110248561/8cd1ca3f-f9f2-49cb-9a1b-4e90d63a4508)

**Comment by hendriknielaender** [comment] 2024-05-20 11:18
@dsus-ch thanks for reporting this issue. I will try to get this reproduce, my first guess is that the `.ReleaseSafe` option currently strips something from the http client request.

**Comment by hendriknielaender** [comment] 2024-06-23 19:39
@dsus-ch we have changed the release mode back to debug in version 0.4.2.  Does this still occur for you in the latest version?

**Comment by hendriknielaender** [comment] 2024-08-05 15:14
Since there have been no updates on this issue and we have had a couple of releases of zvm since it was opened, I am closing this issue. If the problem persists, I am happy to reopen it or create a new issue. Thank you!

**Closed by hendriknielaender** 2024-08-05 15:14 UTC
Labels: bug

**Comment by dsus-ch** [comment] 2024-11-19 05:37
Sorry for missing your notifications! Actually, as you mentioned, the issue seems to have resolved itself after the update. Thanks a lot!
